kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssmcloud-dev-backend-data-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: "generic"
  labels:
    app.kubernetes.io/name: ssmcloud-dev-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
