---
name: Build SSM Cloud Backend
on:
    push:
        tags-ignore:
            - "**"
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -o ./release/linux/ssmcloud-backend .
            - run: if [ ! -f ./release/linux/ssmcloud-backend ]; then exit 1; fi
            - run: mkdir -p ./docker/release >/dev/null && cp ./release/linux/* ./docker/release/.
            - uses: vimtor/action-zip@v1
              with:
                  files: release/linux/ssmcloud-backend
                  recursive: false
                  dest: SSMCloud-Backend-Linux-amd64.zip
            - uses: actions/upload-artifact@v4
              with:
                  name: ssm-build-linux
                  path: ${{ github.workspace }}/SSMCloud-Backend-Linux-amd64.zip
            - name: Get version
              id: versionnum
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./docker
                  push: true
                  tags: mrhid6/ssmcloud-backend:dev
    build-windows:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -o ./release/windows/ssmcloud-backend.exe .
            - uses: vimtor/action-zip@v1
              with:
                  files: release/windows/ssmcloud-backend.exe
                  recursive: false
                  dest: SSMCloud-Backend-Windows-x64.zip
            - uses: actions/upload-artifact@v4
              with:
                  name: ssm-build-win64
                  path: ${{ github.workspace }}/SSMCloud-Backend-Windows-x64.zip
    deploy:
        needs:
            - build-linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Get version
              id: versionnum
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Run a runbook in Octopus Deploy 🐙
              uses: OctopusDeploy/run-runbook-action@v3
              env:
                  OCTOPUS_API_KEY: ${{ secrets.OCTOPUSSERVERAPIKEY  }}
                  OCTOPUS_URL: ${{ secrets.OCTOPUSSERVERURL }}
                  OCTOPUS_SPACE: ${{ secrets.OCTOPUSSERVER_SPACE }}
              with:
                  project: "ssmcloud-backend"
                  runbook: "Deploy SSM Cloud Backend"
                  environments: |
                      Dev
                  variables: |
                      ssmcloud.imagetag:dev
