---
name: Build SSM Cloud Backend
on:
    push:
        tags:
            - "*"
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go 1.23.x
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23.x"
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -o ./release/linux/ssmcloud-backend .
            - run: if [ ! -f ./release/linux/ssmcloud-backend ]; then exit 1; fi
            - run: mkdir -p ./docker/release >/dev/null && cp ./release/linux/* ./docker/release/.
            - uses: vimtor/action-zip@v1
              with:
                  files: release/linux/ssmcloud-backend
                  recursive: false
                  dest: SSMCloud-Backend-Linux-amd64.zip
            - uses: actions/upload-artifact@v1
              with:
                  name: ssm-build
                  path: ${{ github.workspace }}/SSMCloud-Backend-Linux-amd64.zip
            - name: Get version
              id: versionnum
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./docker
                  push: true
                  tags: mrhid6/ssmcloud-backend:latest , mrhid6/ssmcloud-backend:v${{ steps.versionnum.outputs.version }}
    build-windows:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go 1.23.x
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23.x"
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -o ./release/windows/ssmcloud-backend.exe .
            - uses: vimtor/action-zip@v1
              with:
                  files: release/windows/ssmcloud-backend.exe
                  recursive: false
                  dest: SSMCloud-Backend-Windows-x64.zip
            - uses: actions/upload-artifact@v1
              with:
                  name: ssm-build
                  path: ${{ github.workspace }}/SSMCloud-Backend-Windows-x64.zip
    release:
        needs:
            - build-linux
            - build-windows
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download a artifact
              uses: actions/download-artifact@v3
              with:
                  name: ssm-build
            - run: ls -l
            - name: Get version
              id: versionnum
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.versionnum.outputs.version }}
                  release_name: Release v${{ steps.versionnum.outputs.version }}
                  draft: false
                  prerelease: false
            - name: Upload Linux Release Asset
              id: upload-linux-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./SSMCloud-Backend-Linux-amd64.zip
                  asset_name: SSMCloud-Backend-Linux-amd64.zip
                  asset_content_type: application/zip
            - name: Upload Windows Release Asset
              id: upload-win-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./SSMCloud-Backend-Windows-x64.zip
                  asset_name: SSMCloud-Backend-Windows-x64.zip
                  asset_content_type: application/zip
    deploy:
        needs:
            - build-linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Get version
              id: versionnum
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Create and deploy release
              uses: OctopusDeploy/create-release-action@v3
              with:
                  api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
                  server: ${{ secrets.OCTOPUSSERVERURL }}
                  space: ${{ secrets.OCTOPUSSERVER_SPACE }}
                  project: ssmcloud-backend
                  release_number: ${{ steps.versionnum.outputs.version }}
                  deploy_to: Dev
                  progress: false
            - name: Deploy Release
              uses: OctopusDeploy/deploy-release-action@v3
              with:
                  api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
                  server: ${{ secrets.OCTOPUSSERVERURL }}
                  space: ${{ secrets.OCTOPUSSERVER_SPACE }}
                  project: "ssmcloud-backend"
                  release_number: ${{ steps.versionnum.outputs.version }}
                  environments: |
                      Dev
